/** ui */
const ui = {
  SET_FROSTED_GLASS: 'SET_FROSTED_GLASS',
  SET_LOADING: 'SET_LOADING',
};

/** temp */
const scenicspot = {
  SET_SENICSPOT_SEARCH: 'SET_SENICSPOT_SEARCH',
  SET_SENICSPOT_LIST: 'SET_SENICSPOT_LIST',
  SET_CURRENT_SENICSPOT: 'SET_CURRENT_SENICSPOT',
};

export {
  ui, scenicspot,
};
